//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Med
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Descript { get; set; }
        public int Pathologic { get; set; }
        public string Partner { get; set; }
        public string Diognas { get; set; }
        public string Form { get; set; }
        public int Cost { get; set; }
        public double Skidka { get; set; }
    
        public virtual Pathologic Pathologic1 { get; set; }
    }
}
